# Generated by Django 5.0.6 on 2026-08-15 05:32

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Numéro de téléphone au format +2376XXXXXXXX",
                        max_length=20,
                        unique=True,
                        validators=[accounts.models.validate_phone_number],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email (optionnelle)",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(help_text="Prénom", max_length=150)),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom (optionnel)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de profil de l'utilisateur",
                        null=True,
                        upload_to="avatars/%Y/%m/%d/",
                        validators=[accounts.models.validate_image_size],
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Ville", max_length=100, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Localisation complète",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, help_text="Quartier", max_length=150, null=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("admin", "Administrateur"),
                            ("super_admin", "Super Administrateur"),
                        ],
                        default="client",
                        help_text="Rôle de l'utilisateur",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Compte actif"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Accès à l'administration Django"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "Anglais")],
                        default="fr",
                        help_text="Langue préférée",
                        max_length=10,
                    ),
                ),
                (
                    "receive_newsletter",
                    models.BooleanField(
                        default=False, help_text="Recevoir la newsletter"
                    ),
                ),
                (
                    "receive_promotions",
                    models.BooleanField(
                        default=False, help_text="Recevoir les promotions"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, help_text="URL du profil Facebook", null=True
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="URL du profil Instagram", null=True
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, help_text="URL du profil Twitter", null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="URL du profil LinkedIn", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, help_text="Date de dernière activité", null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Code à 6 chiffres", max_length=6)),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")],
                        help_text="Canal d'envoi (SMS ou Email)",
                        max_length=10,
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, help_text="Code déjà utilisé"),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, help_text="Nombre de tentatives"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="Date d'expiration")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code OTP",
                "verbose_name_plural": "Codes OTP",
                "db_table": "otp_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(help_text="Token JWT", max_length=500)),
                (
                    "device_info",
                    models.JSONField(
                        default=dict, help_text="Informations sur l'appareil"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User Agent du navigateur"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Session active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="Date d'expiration")),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, help_text="Dernière activité"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateurs",
                "db_table": "user_sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_phone_n_a3b1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "code"], name="otp_codes_user_id_72b0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["created_at"], name="otp_codes_created_4cefc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["expires_at"], name="otp_codes_expires_348c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="user_sessio_user_id_bb1b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="user_sessio_created_c03f8d_idx"
            ),
        ),
    ]
