# Generated by Django 5.0.6 on 2026-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Article de commande",
                "verbose_name_plural": "Articles de commande",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="Date de finalisation de la commande", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("payment", "Paiement direct"),
                    ("reservation", "Réservation"),
                ],
                default="payment",
                help_text="Type de commande : paiement direct ou réservation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True, help_text="Référence de paiement", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_date",
            field=models.DateField(
                blank=True, help_text="Date de retrait pour une réservation", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_time",
            field=models.TimeField(
                blank=True, help_text="Heure de retrait pour une réservation", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reserved_until",
            field=models.DateTimeField(
                blank=True, help_text="Date limite de retrait", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True, help_text="ID de transaction", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.URLField(
                blank=True, help_text="URL de l'image du produit", null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(
                blank=True,
                help_text="Nom du produit au moment de l'achat",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Payée"),
                    ("shipped", "Expédiée"),
                    ("delivered", "Livrée"),
                    ("cancelled", "Annulée"),
                    ("reserved", "Réservée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
