# Generated by Django 5.0.6 on 2026-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("orange_money", "Orange Money"),
                    ("mtn_money", "MTN Mobile Money"),
                    ("visa", "Visa"),
                    ("reservation", "Réservation"),
                ],
                default="reservation",
                max_length=20,
            ),
        ),
    ]
