# Generated by Django 5.0.6 on 2026-08-15 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Données supplémentaires du paiement",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de finalisation de la commande (paiement ou réservation confirmée)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Référence de paiement (ex: RED-XXXXXXXX)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reserved_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Date limite de retrait (généralement 24h après la réservation)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="ID de transaction du fournisseur de paiement",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="orders_user_id_17dbdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_type"], name="orders_order_t_836422_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_77e2b9_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_reference"], name="orders_payment_5a5a3d_idx"
            ),
        ),
    ]
